name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24
        options: --privileged

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx flake8 mypy

      - name: Lint (flake8)
        run: flake8 .

      - name: Type check (mypy)
        run: mypy .

      - name: Rodar testes
        run: pytest

      - name: build Docker
        run: docker build -t stringutils .

      - name: Smoke Test Docker + Uvicorn
        run: |
          docker run -e PORT=5010 -d -p 5010:5010 --name stringutils_test stringutils

          for i in {1..10}; do
            curl -sf http://localhost:5010/docs && break
            echo "Aguardando app iniciar..."
            sleep 2
          done

          if ! curl -sf http://localhost:5010/docs; then
            echo "Falha ao acessar /docs"
            docker logs stringutils_test
            exit 1
          fi

          docker stop stringutils_test

